#!/bin/bash
# ==============================================================================
# Workspace Setup Module
# ==============================================================================

# Source common functions
MODULE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$MODULE_DIR/common.sh"

# Setup workspace
setup_workspace() {
    log "Setting up workspace..."
    mkdir -p "$WORKSPACE_DIR"
    cd "$WORKSPACE_DIR"
    
    if [ ! -d ".repo" ]; then
        log "Initializing Repo..."
        repo init -u https://android.googlesource.com/kernel/manifest -b common-android13-5.15
        mkdir -p .repo/local_manifests
        # Skip downloading kernel source (using local link)
        cat > .repo/local_manifests/local.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
    <remove-project name="kernel/common" />
</manifest>
EOF
        log "Syncing repo (this may take a while)..."
        repo sync -c -j$(nproc) --no-tags
    fi
    
    # Source Linking
    log "Linking Kernel Source..."
    if [ -L "common" ]; then rm "common"; fi
    if [ -d "common" ]; then mv common "common_backup_$(date +%s)"; fi
    ln -s "$REPO_ROOT" common
    
    # Remove .config from source tree to avoid "source tree is not clean" error
    # The Makefile's outputmakefile target checks if .config exists in srctree during out-of-tree builds
    # Bazel will generate .config from gki_defconfig automatically, so we can safely remove it
    SOURCE_DIR="$REPO_ROOT"
    if [ -f "$SOURCE_DIR/.config" ]; then
        log "Removing .config from source tree (Bazel will regenerate from defconfig)..."
        rm -f "$SOURCE_DIR/.config" "$SOURCE_DIR/.config.old"
        log "Removed .config (will be regenerated by Bazel from gki_defconfig)"
    fi
    
    # Fix: Ensure Clang Toolchain Exists (Manual Fetch if Repo Sync failed)
    if [ ! -d "$CLANG_DIR/$CLANG_VER" ]; then
        warn "Clang $CLANG_VER not found. Fetching manually..."
        mkdir -p "$CLANG_DIR" && cd "$CLANG_DIR"
        git init
        git remote add origin "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86"
        git fetch --depth 1 origin master
        git checkout FETCH_HEAD -- "$CLANG_VER"
        cd "$WORKSPACE_DIR"
    fi
}

# Check dependencies
check_dependencies() {
    log "Checking Dependencies..."
    if [ -f /etc/arch-release ] && ! command -v repo &> /dev/null; then
        log "Installing dependencies..."
        sudo pacman -S --needed --noconfirm base-devel git repo zip unzip curl wget python bc rsync schedtool cpio ncurses libxml2 xmlto inetutils
    fi
}

